theme = "catppuccin_mocha"

[editor]
line-number = "relative"
color-modes = true
bufferline = "always"

[editor.cursor-shape]
insert = "bar"
select = "underline"

[keys.insert]
j = { k = "normal_mode" }

[keys.normal]
"space" = { e = "file_picker_in_current_directory"}

[editor.indent-guides]
render = true

[editor.statusline]
right = ["diagnostics", "selections", "position", "file-encoding", "file-type"]
