theme = "catppuccin_mocha"

[editor]
line-number = "relative"
true-color = true

[editor.cursor-shape]
insert = "bar"

[keys.insert]
j = { k = "normal_mode" }

[keys.normal]
"space" = { e = "file_picker_in_current_directory"}
