[[language]]
name = "html"
formatter = { command = "prettier", args = ["--parser", "html", "--tab-width", "4"] }

[[language]]
name = "css"
formatter = { command = "prettier", args = ["--parser", "css"] }

[[language]]
name = "json"
formatter = { command = "prettier", args = ["--parser", "json"] }

[[language]]
name = "tsx"
auto-format = true
config = { format = { "indentSize" = 4, "convertTabsToSpaces" = true, "semicolons" = "remove" }}

