general.live_config_reload = true

general.import = [
  "/usr/share/alacritty/themes/catppuccin_mocha.toml"
]

[bell]
animation = "EaseOutExpo"
duration = 0

[colors]
draw_bold_text_with_bright_colors = true

[window]
opacity = 0.95 
title = "Alacritty"

[scrolling]
history = 50000

[font]
normal.family = "JetBrainsMono Nerd Font"
normal.style= "Regular"

bold.family = "JetBrainsMono Nerd Font"
bold.style = "Bold"

italic.family = "JetBrainsMono Nerd Font"
italic.style = "Italic"

bold_italic.family = "JetBrainsMono Nerd Font"
bold_italic.style = "Bold Italic"

size = 12.0

[font.offset]
x = 0
y = 0

[mouse]
hide_when_typing = true

[terminal.shell]
program = "/bin/zsh"
