# Configuration for Alacritty, the GPU enhanced terminal emulator.
window:
  opacity: 0.95 
scrolling:
  history: 50000

# Font configuration
font:
  # Normal (roman) font face
  normal:
    family: hack

    # The `style` can be specified to pick a specific face.
    style: Regular

  # Bold font face
  bold:
    # Font family
    #
    # If the bold family is not specified, it will fall back to the
    # value specified for the normal font.
    family: hack

    # The `style` can be specified to pick a specific face.
    style: Bold

  # Italic font face
  italic:
    # Font family
    #
    # If the italic family is not specified, it will fall back to the
    # value specified for the normal font.
    family: hack

    # The `style` can be specified to pick a specific face.
    style: Italic

  # Bold italic font face
  bold_italic:
    # Font family
    #
    # If the bold italic family is not specified, it will fall back to the
    # value specified for the normal font.
    family: monospace

    # The `style` can be specified to pick a specific face.
    style: Bold Italic

  # Point size
  size: 12.0

env:
  TERM: xterm-256color

# Catppuccin!
colors:
  # Default colors
  primary:
    background: '0x1E1D2F'
    foreground: '0xD9E0EE'

  # Colors the cursor will use if `custom_cursor_colors` is true
  cursor:
    text: '0x1E1D2F'
    cursor: '0xF5E0DC'

  # Normal colors
  normal:
    black:   '0x6E6C7E'
    red:     '0xF28FAD'
    green:   '0xABE9B3'
    yellow:  '0xFAE3B0'
    blue:    '0x96CDFB'
    magenta: '0xF5C2E7'
    cyan:    '0x89DCEB'
    white:   '0xD9E0EE'

  # Bright colors
  bright:
    black:   '0x988BA2'
    red:     '0xF28FAD'
    green:   '0xABE9B3'
    yellow:  '0xFAE3B0'
    blue:    '0x96CDFB'
    magenta: '0xF5C2E7'
    cyan:    '0x89DCEB'
    white:   '0xD9E0EE'

  indexed_colors:
    - { index: 16, color: '0xF8BD96' }
    - { index: 17, color: '0xF5E0DC' }

