# Configuration for Alacritty, the GPU enhanced terminal emulator.
window:
  opacity: 0.9

  title: Alacritty

  class:
    instance: Alacritty
    general: Alacritty
scrolling:
  history: 50000

# Font configuration
font:
  # Normal (roman) font face
  normal:
    family: Hack Nerd Font Mono

    # The `style` can be specified to pick a specific face.
    style: Regular

  # Bold font face
  bold:
    # Font family
    #
    # If the bold family is not specified, it will fall back to the
    # value specified for the normal font.
    family: Hack Nerd Font Mono

    # The `style` can be specified to pick a specific face.
    style: Bold

  # Italic font face
  italic:
    # Font family
    #
    # If the italic family is not specified, it will fall back to the
    # value specified for the normal font.
    family: Hack Nerd Font Mono

    # The `style` can be specified to pick a specific face.
    style: Italic

  # Bold italic font face
  bold_italic:
    # Font family
    #
    # If the bold italic family is not specified, it will fall back to the
    # value specified for the normal font.
    family: Hack Nerd Font Mono

    # The `style` can be specified to pick a specific face.
    style: Bold Italic

  # Point size
  size: 12.0

env:
  TERM: xterm-256color

colors:
  # Catppuccin
  primary:
    background: '#1E1D2F'
    foreground: '#D9E0EE'
  cursor:
    text: '#1E1D2F'
    cursor: '#F5E0DC'
  normal:
    black: '#6E6C7E'
    red: '#F28FAD'
    green: '#ABE9B3'
    yellow: '#FAE3B0'
    blue: '#96CDFB'
    magenta: '#F5C2E7'
    cyan: '#89DCEB'
    white: '#D9E0EE'
  bright:
    black: '#988BA2'
    red: '#F28FAD'
    green: '#ABE9B3'
    yellow: '#FAE3B0'
    blue: '#96CDFB'
    magenta: '#F5C2E7'
    cyan: '#89DCEB'
    white: '#D9E0EE'
  indexed_colors:
    - { index: 16, color: '#F8BD96' }
    - { index: 17, color: '#F5E0DC' }

  # Melange
  # primary:
  #   foreground: '#ECE1D7'
  #   background: '#2A2520'
  # normal:
  #   black: '#352F2A'
  #   red: '#B65C60'
  #   green: '#78997A'
  #   yellow: '#EBC06D'
  #   blue: '#9AACCE'
  #   magenta: '#B380B0'
  #   cyan: '#86A3A3'
  #   white: '#A38D78'
  # bright:
  #   black: '#4D453E'
  #   red: '#F17C64'
  #   green: '#99D59D'
  #   yellow: '#EBC06D'
  #   blue: '#9AACCE'
  #   magenta: '#CE9BCB'
  #   cyan: '#88B3B2'
  #   white: '#C1A78E'

