import = [
  "/usr/share/alacritty/themes/gruvbox_material_hard_dark.toml"
]

[window]
opacity = 0.85 
title = "Alacritty"

[scrolling]
history = 50000

[font]
normal.family = "JetBrainsMono Nerd Font Mono"
normal.style= "Regular"

bold.family = "JetBrainsMono Nerd Font Mono"
bold.style = "Bold"

italic.family = "JetBrainsMono Nerd Font Mono"
italic.style = "Italic"

bold_italic.family = "JetBrainsMono Nerd Font Mono"
bold_italic.style = "Bold Italic"

size = 12.0
